import typescript from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import rollupJson from "@rollup/plugin-json";
import commonjs from "@rollup/plugin-commonjs";
import fs from "fs";
import path from "path";

const isProd = process.env.BUILD === "production";

const currentDir = path.dirname(__filename);
const outputDir = path.resolve(currentDir, "../../dist/obsidian-plugin");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
  input: "src/main.ts",
  output: {
    dir: outputDir,
    sourcemap: "inline",
    sourcemapExcludeSources: isProd,
    format: "cjs",
    exports: "default",
    banner,
  },
  external: ["obsidian"],
  plugins: [
    copyPluginAssets(),
    typescript(),
    nodeResolve({ browser: true, extensions: [".mjs", ".js", ".json", ".node", ".ts"] }),
    rollupJson(),
    commonjs(),
  ],
  onwarn(warning, warn) {
    // workaround to prevent rollup build error
    if (
      warning.code === "EVAL" &&
      /.*\/node_modules\/file-type\/.*/.test(warning.loc.file)
    ) {
      return;
    }
    warn(warning);
  },
};

function copyPluginAssets() {
  return {
    name: "copy-plugin-assets",
    buildStart() {
      fs.rmSync(outputDir, { recursive: true, force: true });
      fs.mkdirSync(outputDir, { recursive: true });
      fs.copyFileSync(path.join(currentDir, "manifest.json"), path.join(outputDir, "manifest.json"));
      fs.copyFileSync(path.join(currentDir, "styles.css"), path.join(outputDir, "styles.css"));
    },
  };
}
